### ISSUE TITLE
docusign_maestro not found

### ISSUE THREAD

**Issue by pfennema** [docusign/code-examples-python#38]
When I try to run the examples the run.py does not work as it tries to import docusign_maestro which is not part of the requirements (and nowhere to be found).

**Comment by DocuSignEric** [comment]
Hi Paul,

Unfortunately this is an error that we are having in the python SDK, since Maestro is a new feature that will be revealed in a few weeks, there was a discrepancy and it is causing this error.

Please, to solve this error, you must delete the Maestro folder:

1. Go to <Quickstart> app/
2. Delete the 'master' folder
3. Edit the __init__.py file
4. Search for 'teacher' keyword
5. Delete any line that mentions it.
6. Save the file.
7. Try one more time to start the server

Regards,

Eric | DocuSign

**Comment by pfennema** [comment]
Thanks, indeed I changed the code and the examples now work again.
